### ISSUE TITLE
Add RSS or Atom feed

### ISSUE THREAD

**Issue by jdecool** [sdegutis/sdegutis.com#1]
It could be nice to follow your articles.

**Comment by jaux** [comment]
@sdegutis I also want to add your blog to my feed reader!

**Comment by sdegutis** [comment]
What clients do you guys use? And how did you find my blog?

**Comment by jaux** [comment]
@sdegutis Your clean code article was on hacker news front page.

**Comment by jdecool** [comment]
I use [Tiny Tiny RSS](https://tt-rss.org/) as RSS reader.

You saw your article on hacker news too.

**Comment by sdegutis** [comment]
Oh cool, didn't know it hit FP. Thanks. Adding RSS right now.

**Comment by sdegutis** [comment]
Done. @jdecool, @jaux: does it look reasonable in your readers?

**Comment by jdecool** [comment]
Yes, it's good !

![screenshot-rss](https://user-images.githubusercontent.com/433926/29839093-5d9c9782-8cfd-11e7-8996-1738e129ff29.png)

Thanks.

**Comment by sdegutis** [comment]
Sweet.
